name: Publish Sonic Nozzle demo to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    paths:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Tell CF that the production branch is the main branch
      run: |
        curl --request PATCH \
            "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/flow-dilution" \
            --header "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data "{\"production_branch\": \"main\"}" || true

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Publish to Cloudflare Pages
      uses: sctg-development/pages-action-without-url@v2
      with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: flow-dilution
            directory: dist
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
